### ISSUE TITLE
Verificação da Macro RSS do planet utilizada na Wiki

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/apyb.gerenciamento#100]
Depois de investigar o problema de lentidão da Wiki, verifiquei dois problemas:
1. Erro de permissão no cache de páginas (resolvido)
2. Lentidão na página principal.
A origem da lentidão é:
   `<<RSSReader(Planeta PythonBrasil,http://wiki.python.org.br/planet/atom.xml,allow_html,5)>>`
Que eleva o tempo de execução da página de 0.01s para 13s.

Como alternativa até a solução final, eu retirei esta linha da página principal.

**Comment by lskbr** [comment]
Atualizei o código da macro. Versão anterior no diretório backup: /home/apyb/pythonwiki/share/moin/data/plugin/macro/backup

Nova versão pode ser usada com:
`<<RSSReader(feed="http://wiki.python.org.br/planet/atom.xml", maxEntries=5, allowHtml=False,includeStyle=False)>>`

Mas ainda está muito lento.

**Comment by erichideki** [comment]
Muito bacana Nilo. Obrigado.

**Comment by lskbr** [comment]
Atualizei o feedparser de 5.1.3 para 5.2.1. Melhorou bastante, mas não o suficiente para voltar a página principal. Alguns posts do planet incluem até as fotos no ATOM. Apesar de ter apenas 3MB, a wiki sofre para fazer o parse.
