### ISSUE TITLE
Publicar extratos do Banco do Brasil

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#102]
Meses que ainda estão pendentes:
- 2013 - novembro e dezembro
- 2014 - TODOS
- 2015 - de janeiro a julho

Local de publicação: http://plone.python.org.br:8045/fundacao/associacao/financeiro

**Comment by taniaa** [comment]
Publiquei os que eu tinha por ter acompanhado os pagamentos da conf de 2013:
extrato_apyb_03_2014.pdf
extrato_apyb_01_2014.pdf
extrato_apyb_12_2013.pdf
extrato_apyb_11_2013.pdf

@marcelcaraciolo @renatooliveira @filipeximenes podem pedir para o financeiro da APyB me enviar os demais para eu ajudar com a publicação?

**Comment by filipeximenes** [comment]
Vou te encaminhar @taniaa

**Comment by taniaa** [comment]
Obrigada, @filipeximenes !

Publiquei os que me enviou:
- extrato_apyb_01_2015.pdf
- extrato_apyb_03_2015.pdf
- extrato_apyb_04_2015.pdf
- extrato_apyb_05_2015.pdf
- extrato_apyb_06_2015.pdf
- extrato_apyb_07_2015.pdf

PS: o de Fevereiro/2015 era o de Março...

Logo, concluí 2013 e 2015! \o/ 

Faltam os seguintes meses ainda:
- 2014 - Fevereiro
- 2014 - Abril a Dezembro
- 2015 - tem que manter...

**Comment by filipeximenes** [comment]
@taniaa mandei por email todos de 2014 e fevereiro de 2015.

**Comment by taniaa** [comment]
Terminei de publicar os que enviou por último.

Tudo em dia! Agora é manter ;)

Obrigada, @filipeximenes !!
