### ISSUE TITLE
Publicar última ata da Assembleia Geral (No 009 de 2014)

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#103]
Local para publicação: http://plone.python.org.br:8045/fundacao/associacao/registro/atas

**Comment by taniaa** [comment]
@marcelcaraciolo @renatooliveira @filipeximenes esta ata já foi registrada em Cartório?
Tem que digitalizar e subir para o site da APYB.

Pesquisando no Google, tem isso no repositório GitHub:
https://github.com/pythonbrasil/estatuto/blob/master/assembleia-2014/ata-009-draft.md

A apresentação de 2014 é um arquivo do Keynote...

**Comment by filipeximenes** [comment]
Não tenho esta informação @taniaa.

**Comment by filipeximenes** [comment]
@taniaa já localizamos a ata. Marcel falou que iria digitalizar e nos mandar. Se isto não acontecer, vamos tentar recuperar os documentos e seguimos com a publicação.

**Comment by taniaa** [comment]
Legal!

**Comment by taniaa** [comment]
Me enviaram e publiquei dia 20/10:
http://associacao.python.org.br/associacao/registro/atas/ata-009/view
