### ISSUE TITLE
Publicar conselho deliberativo de 2010, 2011 e 2012

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#104]
Local: http://plone.python.org.br:8045/fundacao/associacao/organizacao/conselho-deliberativo

**Comment by taniaa** [comment]
@filipeximenes É importante ter isso atualizado para a próxima assembleia tb... Pra ter certeza de quem poderia ficar do Conselho ou Suplente.

Conseguem ver isso?

**Comment by filipeximenes** [comment]
Ok! @renatooliveira vai ficar responsável por essa.

**Comment by taniaa** [comment]
@renatooliveira e @filipeximenes  fiz umas alterações lá pro dia 30/08/2016...

Está ok? Podemos fechar a thread ou precisa arrumar algo mais?

**Comment by rougeth** [comment]
Fechando a issue, parece que o trabalho aqui foi feito, certo? Caso não, podemos reabri-la.
