### ISSUE TITLE
Convocar assembleia geral

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#105]
Geralmente ocorre ao final do primeiro dia de evento

**Comment by taniaa** [comment]
Lembrar de resolver a ata anterior, senão acho que terão problemas...
https://github.com/pythonbrasil/apyb.gerenciamento/issues/103

@marcelcaraciolo @filipeximenes @renatooliveira @cadu-leite

**Comment by filipeximenes** [comment]
Feito!

**importante:** de acordo com o capítulo VIII, artigo 35, a convocação deveria ser feita com 30 dias de antecedência, por isso vamos precisar votar para que a assembléia prossiga apesar do descumprimento deste artigo.
