### ISSUE TITLE
Redirecionar para os domínios amigáveis de antes

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#107]
Colocamos todos os sites do servidor com os Plone sites no ar, mas ainda estão com as URLs provisórias. Falta redirecionar para as URLs corretas:

**PythonBrasil[7]**
De:
    http://plone.python.org.br:8045/pythonbrasil
Para: 
    http://2011.pythonbrasil.org.br/
**PS: Hoje está redirecionando para http://2014.pythonbrasil.org.br/**

**PythonBrasil[9] OLD**
Nada a fazer por hora:
    http://plone.python.org.br:8045/pythonbrasil2013

**PythonBrasil[9]**
De:
    PythonBrasil[9] ATUALIZADA - pythonbrasil - http://plone.python.org.br:8080/Plone/pythonbrasil
Para:
    http://2013.pythonbrasil.org.br/pythonbrasil

**PloneConf 2013**
De:
    PloneConf 2013 ATUALIZADA - ploneconf - http://plone.python.org.br:8080/Plone/ploneconf
Para:
    http://2013.pythonbrasil.org.br/ploneconf

**PythonBrasil (da 1 a 6)**
Nada a fazer por hora. **Tem que resolver os problemas antes (ver issue #86)**
    http://plone.python.org.br:8120/pycon

---

**RESOLVIDO Associação Python Brasil**
De:
    http://plone.python.org.br:8045/fundacao
Para:
    http://associacao.python.org.br/

**Comment by filipecifali** [comment]
DNSs alterados 
http://2011.pythonbrasil.org.br funcionando 
http://2013.pythonbrasil.org.br/pythonbrasil funcionando (precisei ajustar o vhost do Apache para funcionar)

http://2013.pythonbrasil.org.br/ploneconf não funcionando (o acesso http://plone.python.org.br:8080/Plone/ploneconf gera erro já)

**Comment by taniaa** [comment]
Praticamente tudo resolvido!

Só este que tem que cair no site da conferência correto... Ele está caindo na conf de 2014:

PythonBrasil[7]
De:
http://plone.python.org.br:8045/pythonbrasil
Para:
http://2011.pythonbrasil.org.br/

**Comment by diegorocha** [comment]
O site desse ano não possui http://2015.pythonbrasil.org.br/ apenas http://pythonbrasil.org.br/ que redireciona para http://pythonbrasil.github.io/pythonbrasil11-site/ 

Não seria o caso de fazer o subdominio 2015 apontar (ou redirecionar) para o site certo também?

**Comment by taniaa** [comment]
Testei todos indicados. Os apontamentos de 2011, 2013 E 2015 estão funcionando.
