### ISSUE TITLE
Publicação da convocação da assembléia 2015 no plone

### ISSUE THREAD

**Issue by filipeximenes** [pythonbrasil/apyb.gerenciamento#112]
# Convocação para a Assembléia Geral da APyB 2015

Assembléia Geral da Associação Python Brasil onde serão realizadas eleições para a Diretoria da Associação bem como a renovação dos Conselhos Deliberativo e Fiscal.
## A Associação Python Brasil (APyB)

A Associação Python Brasil (APyB) tem como meta apoiar as comunidades relacionadas à linguagem Python e suas tecnologias derivadas em todo Brasil. Isso se dá através da organização e apoio a eventos, divulgação da linguagem e casos de sucesso, da manutenção das bases de conhecimento e demais ações promovidas.
## A Assembléia Geral

A Assembléia Geral visa a apresentação da situação atual da Associação Python Brasil, definição de ações para o futuro, sugestões para mudanças no estatuto da Associação e as eleições para renovação da Diretoria e dos Conselhos Deliberativo e Fiscal.
## A convocação

A Associação Python Brasil, através de seu Conselho Deliberativo, vem convidar os seus associados e interessados a participar da sua Assembleia Geral que acontecerá durante a décima primeira edição do encontro brasileiro da comunidade Python, PythonBrasil[11].
## Qualificação dos Participantes

Estão qualificados a atender a Assembleia Geral todos os participantes da PythonBrasil[11], assim como os  membros associados a APyB independente de estarem ou não inscritos no evento. Durante a Assembléia Geral o direito a voto fica reservado apenas aos associados em situação regular conforme definido nos artigos quarto, quinto e sexto do Estatuto da Associação.
## Processo de Filiação

A filiação pode ser feita através do site da associação[1] e está aberta a todos os interessados. Para se associar basta preencher o formulário de inscrição e efetuar o pagamento da anuidade. As modalidades de associação disponíveis e os respectivos valores de anuidade são:

Profissional: R$ 64,00
Estudante: R$ 32,00
## A eleição da Diretoria

Durante a assembléia será realizada as eleição para a nova Diretoria da APyB. O mandato é de 2 anos e cada chapa deve ter: 1 Presidente, 1 Diretor de Tecnologia, 1 Diretor de Marketing e 1 Diretor Financeiro.
Todos os membros em situação regular à associação estão aptos a formar chapas e a concorrer. As chapas devem se apresentar durante a assembléia, mas é de grande valor que realizem campanha com antecedência para que a comunidade conheça os membros e propostas.
## Data e Hora

Terça-feira, dia 10 de novembro de 2015, às 16:50.
## Local da Assembléia

PythonBrasil[11] - Novotel - São José dos Campos/SP

[1] http://associados.python.org.br/

Atenciosamente,
Filipe de Alencar Ximenes
Diretor de Marketing da Associação Python Brasil

**Comment by taniaa** [comment]
Publicado, com pequenos ajustes no texto, como Assembleia sem acento, conferência (ao invés de encontro), ...

http://associacao.python.org.br/associacao/imprensa/noticias/convocacao-para-a-assembleia-geral-da-apyb-2015
