### ISSUE TITLE
http://br.pycon.org/ aponta para a PythonBrasil 2014

### ISSUE THREAD

**Issue by diegorocha** [pythonbrasil/apyb.gerenciamento#113]
Existe um direcionamento http://br.pycon.org/ só que o mesmo está apontando pro site de 2014 que não é o mais recente.

nslookup br.pycon.org
Server:     192.168.1.1
Address:    192.168.1.1#53

Non-authoritative answer:
br.pycon.org    canonical name = www.pythonbrasil.org.br.
Name:   www.pythonbrasil.org.br
Address: 104.130.163.103

Embora o cname aponte para www.pythonbrasil.org.br (que é o site mais recente) ao jogar http://br.pycon.org/ no browser abre o site de 2014. Acredito que seja necessario alguma configuração a mais para que ele direcione pro site mais recente (Github pages).

**Comment by filipecifali** [comment]
@sergiomario pode ver se configurando o github pages pra 2016 ele funciona? 

@diegorocha essa URL ainda é relevante? Ela precisa existir?

**Comment by sergiomario** [comment]
@filipecifali Já coloquei o domínio br.pycon.org no CNAME do nosso gh-pages.

**Comment by diegorocha** [comment]
@filipecifali é o padrão da comunidade internacional. Mas não acho que deve ter tanta gente que chega no site por esse tipo de url não.

**Comment by filipecifali** [comment]
Adicionei o server_name dentro da config do nginx, como não existia conf antes ele caia em um matching do ultimo vhost criado que era o de 2014. 

Resolvido.
