### ISSUE TITLE
Acertar link para a PythonBrasil no site da PSF

### ISSUE THREAD

**Issue by diegorocha** [pythonbrasil/apyb.gerenciamento#114]
No site da PSF existe uma lista de conferências sobre Python  em https://www.python.org/community/workshops/

O site brasileiro aponta para http://pyconbrasil.com.br/ (e o nome está antigo).

Imagino que seja só enviar um e-mail para a PSF que eles acertem, mas o ideal é que alguém da apyb que mande esse e-mail para dar mais credibilidade.

> If you have an event to add to this page, please write to (pydotorg-www at python dot org).

**Comment by rochacbruno** [comment]
Precisa abrir uma issue nesse repo: https://github.com/python/pythondotorg/issues

**Comment by diegorocha** [comment]
Seguindo o que o @rochacbruno disse criei a issue https://github.com/python/pythondotorg/issues/860

**Comment by rochacbruno** [comment]
:+1: foi resolvido!
