### ISSUE TITLE
Corrigir sobrenome do David Beazley na edição do video do Youtube (está escrito com S e não com Z)

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/apyb.gerenciamento#115]
Corrigir sobrenome do David Beazley na edição do vídeo(11s) do Youtube (está escrito com S e não com Z),

Tambem corrigir na descrição do video

https://www.youtube.com/watch?v=ZzfHjytDceU&index=5&list=PLDC3uVLxaEQ1WF1CbdDbUJ9nudBsKhTdi

@cadu-leite

**Comment by filipecifali** [comment]
@luzfcb agora você tem o poder! (ainda está errado?)

**Comment by luzfcb** [comment]
@filipecifali está errado no video e não na descrição ou titulo no youtube. Teria que editar o vídeo, corrigir e fazer upload novamente...

https://youtu.be/ZzfHjytDceU?t=10s

não sei se há como fazer isso no youtube...

**Comment by filipecifali** [comment]
Puts... fica muito feio por uma daquelas box de texto por cima? :disappointed:

**Comment by diegorocha** [comment]
Acho que é uma saída viável. Dentro do Box informar que o nome embedado no
vídeo está errado, e dizer o certo. Muitos canais "profissionais" fazem
isso.

**Comment by luzfcb** [comment]
Fiz a mudança.... tá online (não gostei).... https://youtu.be/ZzfHjytDceU?t=7s
