### ISSUE TITLE
Criar subdominio para o PyNorte

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/apyb.gerenciamento#116]
Olá, eu estou com o grupo PyNorte do Telegram. Como os grupos do norte são poucos, a ideia seria ter uma página única por enquanto. Estamos usando o stub do grupy-df.
O págia foi levantada aqui: 
http://lskbr.github.io/grupybr-pynorte/
Não sei como ficaria o subdomínio:
pynorte.python.org ou
pynorte.am.python.org ?

**Comment by diegorocha** [comment]
Acho que pynorte.python.org.br faz mais sentido, pois não é um sub grupo local de um estado (como é o floripa.sc.python.org.br), e sim um grupo de vários estados

**Comment by filipecifali** [comment]
A pergunta real é: qual vocês preferem?

Nós temos subdomínios de outros grupos também (como pug-pe / pug-ce).python.org.br

Escolham e informem para onde deve estar apontado.

**Comment by lskbr** [comment]
pynorte.python.org.br é perfeito.

Obrigado pela resposta rápida.

**Comment by filipecifali** [comment]
O mais importante, para onde aponto ele? 

Vai ficar na página http://lskbr.github.io/grupybr-pynorte/ mesmo?

**Comment by luzfcb** [comment]
@lskbr como faz para entrar no grupo do Telegram PyNorte? (sou newbie de telegram)... Te mandei um convite do Hangouts

**Comment by diegorocha** [comment]
@lskbr coloca no site um link para o invite link do grupo do telegram!

**Comment by filipecifali** [comment]
Apontamento criado via CNAME:

;; ANSWER SECTION:
pynorte.python.org.br.  3600    IN  CNAME   lskbr.github.io.
lskbr.github.io.    3192    IN  CNAME   github.map.fastly.net.
github.map.fastly.net.  30  IN  A   199.27.76.133

Acho que tem que criar o arquivo lá no repositório agora, qualquer coisa faço outra alteração depois.

**Comment by lskbr** [comment]
Opa, muito obrigado, já está funcionando.
Para entrar no grupo do Telegram, segue o Link: https://telegram.me/joinchat/COYq6QM8RkebVUVK1WxRHQ
