### ISSUE TITLE
Mudar domínio da PyNorte

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/apyb.gerenciamento#117]
Olá,

Nós estamos nos reorganizando e acabamos por criar uma organização no GitHub.
Por favor apontar o pynorte.python.org.br para http://pynorte.github.io/grupybr-pynorte/

Obrigado,

Nilo

**Comment by filipecifali** [comment]
Mudança de DNS efetuada:

pynorte.python.org.br
CNAME
pynorte.github.io
None

Basta aguardar o TTL de cache vencer.
