### ISSUE TITLE
Criar subdominios para o PythOnRio

### ISSUE THREAD

**Issue by diegorocha** [pythonbrasil/apyb.gerenciamento#118]
O PythOnRio está reformulando a sua página no gh-pages (pythonrio.github.io).
O grupo tem interesse em dois subdominios: rj.python.org.br e pythonrio.python.org.br, o primeiro é para manter o padrão da comunidade e o segundo pois o grupo possui um nome peculiar mas que já bastante antigo e conhecido.

Resumindo: peço que sejam criados dois registros cname no dns python.org.br
rj e pythonrio ambos apontando para pythonrio.github.io.

**Comment by filipecifali** [comment]
CNAMEs criados, já estão resolvendo ao nome certo:

dig @4.2.2.2 pythonrio.python.org.br                                                                                     [09:47:57]

; <<>> DiG 9.8.3-P1 <<>> @4.2.2.2 pythonrio.python.org.br
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31423
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pythonrio.python.org.br.   IN  A

;; ANSWER SECTION:
pythonrio.python.org.br. 3600   IN  CNAME   pythonrio.github.io.
pythonrio.github.io.    3600    IN  CNAME   github.map.fastly.net.
github.map.fastly.net.  29  IN  A   199.27.76.133

;; Query time: 172 msec
;; SERVER: 4.2.2.2#53(4.2.2.2)
;; WHEN: Wed Mar  9 09:47:57 2016
;; MSG SIZE  rcvd: 125

dig @4.2.2.2 rj.python.org.br                                                                                            [09:48:03]

; <<>> DiG 9.8.3-P1 <<>> @4.2.2.2 rj.python.org.br
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39613
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;rj.python.org.br.      IN  A

;; ANSWER SECTION:
rj.python.org.br.   3600    IN  CNAME   pythonrio.github.io.
pythonrio.github.io.    3600    IN  CNAME   github.map.fastly.net.
github.map.fastly.net.  28  IN  A   199.27.76.133

;; Query time: 169 msec
;; SERVER: 4.2.2.2#53(4.2.2.2)
;; WHEN: Wed Mar  9 09:48:03 2016
;; MSG SIZE  rcvd: 118
