### ISSUE TITLE
Inclusão do Blog Catholabs no Planet

### ISSUE THREAD

**Issue by rochacbruno** [pythonbrasil/apyb.gerenciamento#119]
Olá,

Gostaria de adicionar o feed: http://catholabs.com/tag/python.atom no Python Planet Brasil. Obrigado

**Comment by rochacbruno** [comment]
1 year old.. closing..

**Comment by filipecifali** [comment]
Desculpa a demora @rochacbruno, agora esse trabalho ficou menos burocratico: https://github.com/pythonbrasil/planet (já adicionei o Catho labs lá)

**Comment by rochacbruno** [comment]
valeu!
