### ISSUE TITLE
subdomínio para o evento Caipyra 2016

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/apyb.gerenciamento#120]
@filipecifali por gentileza, add a configuração abaixo ao dns do python.org.br:

`CNAME caipyra.python.org.br -> grupyrp.github.io`

valeu! (:

**Comment by filipecifali** [comment]
Feito!

dig caipyra.python.org.br +short
grupyrp.github.io.
github.map.fastly.net.
199.27.79.133
