### ISSUE TITLE
Redirecionar conteúdo da wiki atual (MoinMoin)

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#121]
Novo hostname será old.wiki.python.org.br até não ser mais necessária

**Comment by taniaa** [comment]
Oi, @filipecifali !

O novo site python.org.br está no GitHub e no ar.

Mas o site antigo (old.wiki.python.org.br) agora aponta para a conferência PythonBrasil10...

Consegue apontar pro Moin Moin pra eu ver e migrar uns conteúdos?

**Comment by filipecifali** [comment]
@taniaa 

Esse ainda não foi movido, está todo em: wiki.python.org.br/ rodando o moinmoin antigo

ainda tem muito conteúdo que não está no site novo

**Comment by humrochagf** [comment]
seria legal mapear o que precisa ser migrado, eu fico meio perdido dentro da wiki antiga, se tiver uma relação do que precisa ser migrado se pá numa sentada eu resolvo essa parada

**Comment by taniaa** [comment]
@humrochagf eu entendo bastante da estrutura do antigo... Podemos fazer um sprint e fechar isso em BH. Você vai pra PythonBrasil13? Senão estou disponível pra qq sábado de manhã destes...

**Comment by humrochagf** [comment]
legal, podemos marcar um dia no calango, após o dojo podemos dar uma primeira olhada

**Comment by taniaa** [comment]
Combinado!

**Comment by rougeth** [comment]
Fechando a issue. Site antigo está em wiki.python.org.br.
