### ISSUE TITLE
Configurar sites no server01.python.org.br

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#123]
Migrar os vhosts de Nginx e Lighttpd para Apache2, ficando no padrão somente um webserver para reduzir complexidade de uso e consumo de memória.

**Comment by filipecifali** [comment]
Estão sendo armazenadas em /etc/apache2/sites-available para depois irem para sites-enabled assim que estiverem todas configuradas para mais tarde mudar o DNS dos sites

**Comment by luzfcb** [comment]
pergunta: mas Apache não costuma gastar mais memoria RAM a medida que aumenta a quantidade de pessoas simultaneamente acessando ele? Lembro-me que essa era uma das desvantagens dele em relação ao Nginx (não sei a quantidade de conexões que isso vira algo com alguma importância real.)

**Comment by filipecifali** [comment]
@luzfcb Não temos acessos o bastante para isso vir a ser um problema, hoje temos a maior parte do consumo de RAM pelas instâncias de Zope apenas, os webservers mal são tocados e com a constante mudança dos sites para o github.io menos são usados.

**Comment by filipecifali** [comment]
Site django.org.br e djangobrasil migrados para o server01. 
 Falta agora migrar o Nginx do 104.130.163.103 só e ainda vamos ter recursos sobrando no final da coisa toda.

**Comment by rochacon** [comment]
@humrochagf @filipecifali esta migração terminou? Esta issue ainda é relevante (e a #121)?

Tenho recebido e-mails frequentes do monitoramento configurado na Rackspace sobre downtime da wiki, mas me parece que tanto a wiki quanto o site foram migrados para um servidor da Cloudez [1].
Não encontrei issue ou e-mail sobre esta mudança mas posso não estar registrado nos canais que as discussões ocorreram, estive afastado das atividades da APyB a um bom tempo.

Se não estamos mais usando a Rackspace, podemos desligar esta monitoração? Talvez também os servidores?

[1] 

```
$ nslookup python.org.br 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	python.org.br
Address: 45.33.120.99

$ nslookup wiki.python.org.br 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
wiki.python.org.br	canonical name = ip-45-33-120-99.cloudezapp.io.
Name:	ip-45-33-120-99.cloudezapp.io
Address: 45.33.120.99
```

**Comment by humrochagf** [comment]
Ah, sim @rochacon pode desligar a notificação eu estou tocando a migração para a infra aqui da empresa que disponibilizou a estrutura de hospedagem monitoramento e automação para os sites da APyB e meu tempo para tocar o processo.

Já consegui resgatar os sites antigos dos eventos e já concluí a migração e instalação de https em todos os sites de eventos dês da primeira pycon até a deste ano, o site python.org.br e ontem concluí a wiki.

Ainda preciso revisar algumas coisas para poder começar o desligamento dos servidores antigos por completo mas o alerta já pode ser desativado sim. :)

**Comment by rochacon** [comment]
@humrochagf boa! Eu desliguei as notificações mas deixei o [monitor](https://intelligence.rackspace.com/cloud/entities/enqGntnODf/checks/cht4lCqJMw) rodando, até que migremos ele para a nova infra ou outro serviço, assim não perdemos os dados de uptime. 😉

**Comment by rougeth** [comment]
Fechando a issue, já que a migração do Rackspace foi concluída.
