### ISSUE TITLE
Inclusão do Blog do Diego Garcia no Planet

### ISSUE THREAD

**Issue by drgarcia1986** [pythonbrasil/apyb.gerenciamento#124]
Gostaria de adicionar meu blog (mais precisamente o [feed sobre python](http://www.diego-garcia.info/python.atom.xml)) na lista do Python Planet Brasil.

Muito obrigado.

**Comment by filipecifali** [comment]
Oi Garcia, inclui teu blog de maneira automática aqui: https://github.com/pythonbrasil/planet 

Primeiro commit de testes :+1:

**Comment by diegorocha** [comment]
O planet já está lendo do arquivo desse repo?!

Se sim, que legal! Vai ficar muito mais fácil esse tipo de inclusão!

**Comment by drgarcia1986** [comment]
que legal, muito obrigado @filipecifali 👍
