### ISSUE TITLE
Verificar problema com contato do site da Associação

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#126]
Em teste que fiz, não deu erro (aparentemente) no envio, mas não recebi o mail.

Verificar config do servidor SMTP e log de erros do servidor.

**Comment by filipecifali** [comment]
Postfix configurado e Plone configurado para fazer o envio, disparei alguns testes e a princípio, ok!

**Comment by taniaa** [comment]
Testado. Obrigada!
