### ISSUE TITLE
Criar subdomínio se.python.org.br (Python User Group Sergipe)

### ISSUE THREAD

**Issue by rodrigoamaral** [pythonbrasil/apyb.gerenciamento#128]
O PUG-SE solicita criação de subdomínio se.python.org.br apontando para http://pug-se.github.io

**Comment by filipecifali** [comment]
Registro modificado, não esqueça de colocar no projeto a configuração do domínio.

TTL de 60min

**Comment by rodrigoamaral** [comment]
Obrigado!

## 

Rodrigo Amaral
rodrigoamaral@gmail.com
