### ISSUE TITLE
Inclusão do blog do Henrique Lopes no planet

### ISSUE THREAD

**Issue by riquellopes** [pythonbrasil/apyb.gerenciamento#129]
Gostaria adicionar meu blog https://medium.com/feed/@riquellopes/ na lista do Python Planet.

Obrigado.

**Comment by filipecifali** [comment]
Oi @riquellopes, você pode fazer diretamente através deste repositório: https://github.com/pythonbrasil/planet basta mandar um pull request com seus dados lá!
