### ISSUE TITLE
Python Planet - Redirect para página que não existe.

### ISSUE THREAD

**Issue by riquellopes** [pythonbrasil/apyb.gerenciamento#130]
No site da [PlanetPython](http://planetpython.org/) na categoria **Other Python Planets** o [Planet Python Brasil](http://wiki.python.org.br/planet/) está sendo direcionado para o domínio errado. http://python.org.br/planet/

**Comment by filipecifali** [comment]
Gerado PR no repositório deles: https://github.com/python/planet/pull/210

Obrigado pelo aviso @riquellopes
