### ISSUE TITLE
Adicionar blog ao Planeta PythonBrasil

### ISSUE THREAD

**Issue by paulohrpinheiro** [pythonbrasil/apyb.gerenciamento#132]
Por favor, poderiam adicionar esse feed ao agregador:

`https://paulohrpinheiro.xyz/feed.xml`

Obrigado

**Comment by rougeth** [comment]
Planeta Python Brasil não está mais disponível.

**Comment by rougeth** [comment]
Na verdade, Planet ainda está disponível em: https://planet.python.org.br/. Vou mander a issue fechada de qualquer forma. @paulohrpinheiro se ainda tiver interesse, abre um PR no site adicionando o seu feed.
