### ISSUE TITLE
Subir logos restantes das conferências

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#133]
Atualmente faltam da PythonBrasil 10 (Porto de Galinhas/PE), 11 (São José dos Campos/SP) e 13 (Belo Horizonte/MG).

Subir para o site da Associação Python Brasil:
http://associacao.python.org.br/associacao/imprensa/logomarcas/logo-das-versoes-do-evento

**Comment by rougeth** [comment]
Issue replicada no repositório do manual da Python Brasil.
