### ISSUE TITLE
Horário do servidor - URGENTE

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#40]
Verificar o horário do servidor onde está o site 2013.pythonbrasil.org.br.

Notei que os itens estão com data do mês de junho ao invés de abril:
http://2013.pythonbrasil.org.br/recently_modified?b_start:int=20

**Comment by decko** [comment]
@humrochagf @taniaa e @rudaporto o problema foi resolvido? Podemos fechar esta issue?

**Comment by taniaa** [comment]
O servidor foi desligado. Creio que sim

**Comment by decko** [comment]
:+1:
