### ISSUE TITLE
Transferir web2py.com.br para APyB

### ISSUE THREAD

**Issue by turicas** [pythonbrasil/apyb.gerenciamento#46]
O @rochacbruno sugeriu que eu transferisse o domínio web2py.com.br (que eu registrei há alguns anos) para a entidade da APyB no registro.br. A ideia é que fique mais fácil gerenciar os domínios usados pela comunidade, mesmo quando membros parem de contribuir com determinados projetos (que foi justamente o meu caso: atualmente não contribuo com o web2py e o Bruno contribui bastante).

[De acordo com o registro.br](http://registro.br/suporte/procedimentos/transferencia_de_dominio.html), preciso enviar uma carta com alguns documentos meus e da APyB para fazer a transferência. Sendo assim, preciso que @osantana providencie para mim:

- Cópia do CNPJ
- Um dos seguintes documentos:
    - Contrato social, juntamente com as últimas alterações sobre a cláusula de administração/gerência, ou última alteração contratual consolidada, OU
    - Estatuto e ata de eleição da atual diretoria; OU
    - Requerimento de empresário ou declaração de firma individual; OU
    - Procuração de fé pública (estabelecida em cartório) com o fim específico para a transferência do domínio da entidade (quando a pessoa que irá assinar a carta não for o representante legal da entidade).

**Comment by diegorocha** [comment]
Essa issue ainda é válida?! Consultei o https://registro.br/cgi-bin/whois/ e o registro atualmente está vinculado a "Last One Tecnologia LTDA"

**Comment by taniaa** [comment]
Acredito que não faça mais sentido. Certo, @rochacbruno?

**Comment by rochacbruno** [comment]
@taniaa acho que não, e de qualquer forma agora daria mais trabalho para requerer o dominio.

**Comment by taniaa** [comment]
Então, ticket cancelado...
