### ISSUE TITLE
Aumentar espaço em disco nas máquinas da APyB

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#49]
Hoje o Squid ficou fora e o Rudá excluiu um Data.fs.old por hora. Mas deve haver a solução definitiva de aumentar o disco na máquina que serve o site da APyB, edições anteriores do evento Python Brasil, etc.

**Comment by filipecifali** [comment]
O ideal é transformar o site depois do evento para conteúdo estático.

Como estamos com servidores novos, estou fechando esta issue.
