### ISSUE TITLE
Renovar certificado do Python.org.br que está expirado 

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#56]
Como o Ramalho disse na lista apyb-associados, o certificado do Python.org.br expirou em abril de 2013.

Referências:
* A globalsign esta dando certificados SSL free para projetos open-source e comunidades https://www.globalsign.com/pt-br/
* Inscrição em: https://www.globalsign.com/ssl/ssl-open-source/

**Comment by taniaa** [comment]
@filipecifali @renatooliveira como está isso no novo servidor? Ainda precisa dessa issue?

**Comment by mazulo** [comment]
Não sei se realmente ajudaria, mas o [Let's Encrypt](https://letsencrypt.org/2015/10/19/lets-encrypt-is-trusted.html) poderia ajudar nos certificados (caso ainda não esteja resolvida).

cc @taniaa @filipecifali

**Comment by taniaa** [comment]
@filipecifali e @lskbr, 
Sabem nos informar em que pé está isso?
Abraço

**Comment by filipecifali** [comment]
@taniaa Vou olhar hoje a noite a situação do certificado, o Letsencrypt abriu beta para algumas pessoas, mas não sei se está "open beta" já.

**Comment by filipecifali** [comment]
Repositório instalado em: /usr/local/install/letsencrypt

Certificados gerados em standalone:

wiki.apybr: nginx

./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d python.org.br,www.python.org.br,wiki.python.org.br
./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d pythonbrasil.org.br,2012.pythonbrasil.org.br,2014.pythonbrasil.org.br,www.pythonbrasil.org.br #2015.pythonbrasil.org.br
./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d www.pythonbrasil.com.br

plone.apybr: apache2

./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d associacao.pythonbrasil.org.br #fundacao.pythonbrasil.org.br,zope.pythonbrasil.org.br
./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d associacao.python.org.br #fundacao.python.org.br,tchezope.python.org.br
./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d 2011.pythonbrasil.org.br,2013.pythonbrasil.org.br #old.pythonbrasil.org.br
#./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d associacao.pythonbrasil.com.br,fundacao.pythonbrasil.com.br #nao deu
./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d plone.org.br,www.plone.org.br,downloads.plone.org.br

djangobr: apache2 lighttpd

./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d django.org.br,docs.django.org.br #media.django.org.br
./letsencrypt-auto certonly --standalone --agree-tos --redirect --duplicate --text --email sites@python.org.br -d djangobrasil.org,djangobrasil.org #media.djangobrasil.org,docs

Faltaram algumas coisas mas tudo que o possível está em HTTPS agora usando, para renovar ele basta re-gerar o letsencrypt-auto
