### ISSUE TITLE
Gostaria de incluir o meu blog sobre Python, o www.empython.com, no planeta PythonBrasil.

### ISSUE THREAD

**Issue by sergiofasilva** [pythonbrasil/apyb.gerenciamento#58]

**Comment by rudaporto** [comment]
@sergiofasilva preciso do caminho completo do feed com o filtro para temas relativos a python apenas.

**Comment by sergiofasilva** [comment]
Olá.

O feed relativo a python é o seguinte:
http://www.sergiofasilva.com/feed/python


Cumprimentos,
Sérgio

On Wed, Jan 28, 2015 at 5:47 AM, Rudá Porto Filgueiras <
notifications@github.com> wrote:

> @sergiofasilva <https://github.com/sergiofasilva> preciso do caminho
> completo do feed com o filtro para temas relativos a python apenas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonbrasil/apyb.gerenciamento/issues/58#issuecomment-71784623>
> .
>



-- 
Sérgio Silva
http://www.sergiofasilva.com <http://www.sergiosilvablog.com>

**Comment by rudaporto** [comment]
Incluso.
