### ISSUE TITLE
Pedido de inclusão no planeta-python

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/apyb.gerenciamento#67]
Olá,

Eu gostaria de participar do planeta Python.

Blog:
http://junglecoders.blogspot.be/

Tag:
python

Obrigado,

Nilo Menezes

**Comment by rudaporto** [comment]
Fala Nilo!

Como passa a tag python para o feed? Se tiver a URL facilita.

**Comment by rudaporto** [comment]
Achei a resposta:
- https://support.google.com/blogger/answer/53336?hl=en

Então ficou assim a URL de filtro:
- http://junglecoders.blogspot.be/feeds/posts/default/-/python

**Comment by rudaporto** [comment]
Blog incluso no Planet.
