### ISSUE TITLE
Contatar a Rackspace para criar conta da apyb

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#69]
Limite de custo de 2.000 USD por 1 ano gratuitamente

**Comment by filipecifali** [comment]
São 2 máquinas a princípio, pelo que li dos serviços, precisamos de 2 Cloud Servers com as configs descritas no documento.

**Comment by rudaporto** [comment]
Foi criada a conta com email sites@python.org.br, esse email é um "grupo" no Google Apps da APyB.

Em seguida foi enviado um email com os dados da conta criada para a Dana, e também os links e informações dos sites que temos.

Após o envio do email, ainda não tivemos retorno da Dana a respeito, segue o email enviado abaixo:

> Hi Dana,
>
>First of all, I would like to thank you for your help to get APyB
>(Python Brasil Association) into Rackspace's OSS hosting program!
>
>I created the APyB account (Managed Infrastructure service level),
>follow the account ID 944314.
>We have many sites and a few of them is offline after a problem with
>our old service provider.
>
>Follow the most important with brief comments:

>- wiki.python.org.br (Central Wiki of PythonBrasil community and also
>host a Planet - RSS Blog aggregator)
>- associados.python.org.br (Django App that control Association
>Membership subscriptions and payments)
>- 2014.pythonbrasil.org.br (Python Brasil annual Conference, 2014 event site)
>- [2010,2011,2012,2013].pythonbrasil.org.br (2010 to 2013 Python
>Brasil annual Conference Sites - all offline at moment)
>- old.pythonbrasil.org.br (2005 to 2009 Python Brasil annual
>Conference Sites - offline at moment)
>- plone.org.br (Plone Brasil Community Portal - offline at moment)
>- djangobrasil.org (Django Brasil Communty Portal - offline at moment)
>
>We are working to put all these offline sites online again and manage
>them in one single service.
>
>I'm very excited to use RackSpace's services and the OSS hosting
>program is amazing, thank you again!
>
>Cheers,

**Comment by rudaporto** [comment]
Também no grupo sites@python.org.br foram cadastrados todos que confirmaram presença na primeira reunião.

**Comment by rudaporto** [comment]
Dana retornou com informações que a Conta que eu criei foi encerrada pois não conseguiram confirmar por telefone.

Está em processo de reativar a conta e liberar a mesma, assim que tivermos essa confirmação o crédito será concedido.

**Comment by rochacon** [comment]
Já temos a conta. @rudaporto podemos fechar este issue, certo?

**Comment by rudaporto** [comment]
Yeap! Serviço funcional e com GRANT ;-)
