### ISSUE TITLE
Modificar ambiente utilizado pelos sites da apyb

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#70]
Unificar: Plone da associação + plone.org.br + PlonePythonBrasil/PloneConf 2013
Separar: Djangobrasil.org
Tornar estático: old.pythonbrasil.org.br

Recursos necessários:
1 x 4vCPU 4GB RAM (hostname sugerido: apybs01.pythonbrasil.org.br)
1 x 2vCPU 2GB RAM (hostname sugerido: apybs02.pythonbrasil.org.br)

apybs01 - sites unificados no plone
apybs02 - sites djangobrasil + old + sites da pythonbrasil 2012 e 2014

Como serão clouds e não físicos, em teoria será fácil realocar os recursos com baixo downtime caso necessário.

**Comment by rudaporto** [comment]
Esse ticket é um EPIC.

Agora que temos um espaço no RackSpace, foram criados já um servidor para wiki outro para os Plones, falta apenas o ambiente para o Django.

Vou manter esse ticket aberto até que todos os outros que detalham cada etapa sejam fechados.

**Comment by filipecifali** [comment]
Djangobrasil.org ainda pendente de DNS, online: django.org.br

**Comment by filipecifali** [comment]
djangobrasil.org ok

**Comment by taniaa** [comment]
Oi, @filipecifali no sprint de hoje conseguimos colocar os sites no ar:
- PythonBrasil[7] - http://plone.python.org.br:8045/pythonbrasil
- Associação Python Brasil - http://plone.python.org.br:8045/fundacao
- PythonBrasil[9] OLD - http://plone.python.org.br:8045/pythonbrasil2013
- PythonBrasil[9] ATUALIZADA - pythonbrasil - http://plone.python.org.br:8080/Plone/pythonbrasil
- PloneConf 2013 ATUALIZADA - ploneconf - http://plone.python.org.br:8080/Plone/ploneconf
- PythonBrasil (da 1 a 6) - http://plone.python.org.br:8120/pycon (com problemas, ver issue #86)

Acredita que tenha mais alguma pendência para esta issue fechar?

**Comment by filipecifali** [comment]
@taniaa 

Acredito já podermos fechar ela e criar uma nova para consolidação dos recursos. Obrigado :)

**Comment by taniaa** [comment]
Isso @filipecifali! Estou abrindo umas menores, tipo backup dos ambientes que funcionam, etc.

**Comment by filipecifali** [comment]
Associacao.python.org.br - Configurei o DNS para apontar para o servidor plone.apybr e modifiquei a configuração do Apache para a nova porta para deixar o acesso normal pela URL antiga :+1:
