### ISSUE TITLE
Restauração do Plone PythonBrasil/PloneConf

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#71]
Temos o conteúdo do site armazenado no backup: 

root@li68-189:/backup/zopebrasil/home/apyb# ls la vs42-apyb.tgz 
-rw-r--r- 1 root root 5693490578 Nov 6 19:28 vs42-apyb.tgz
Data => /home/maza/

Precisamos restaurar este plone, possilvemente sejá só o caso de iniciar ele, visto que os dados do OS inteiro estão ali, sendo necessário replicar o virtualhost e subir o Plone

**Comment by rudaporto** [comment]
Esse Plone será restaurado na VM de Plone nova no RackSpace, a issue #73 trata da preparação do ambiente necessário para subir esse site novamente.

**Comment by filipecifali** [comment]
Progresso em #78

**Comment by taniaa** [comment]
Site da PythonBrasil[9] / PloneConf 2013 no ar! Com a ajudazona do grande Rudá! \o/
- PythonBrasil[9](OLD) - http://plone.python.org.br:8045/pythonbrasil2013
- PythonBrasil[9](ATUALIZADA) - pythonbrasil - http://plone.python.org.br:8080/Plone/ploneconf
- PythonBrasil[9](ATUALIZADA) - ploneconf - http://plone.python.org.br:8080/Plone/pythonbrasil
