### ISSUE TITLE
Cron do planet nao esta rodando

### ISSUE THREAD

**Issue by avelino** [pythonbrasil/apyb.gerenciamento#72]
Acredito que o processo de pegar os blogposts dos feed nao esta rodando!

**Comment by rudaporto** [comment]
@avelino acredito que consegui resolver o problema, porém vários blogs precisam ser incluídos (ver issues) e outros estão quebrados e precisam ser corrigidos.

Você pode ajudar nessa revisão? Me passa sua chave pública para acessar via ssh o servidor se puder trabalhar nisso.

**Comment by avelino** [comment]
Ajuda com maior prazer cara:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5OfVvY6xmZdtw5pYJMECnfRfMm7zWMytg+IL9AyNhbu8UdBmGdT6wUiBBBw9CTcdnmDYj08n8gWXV6Jz2eazl7fC27HQr9BzJb35FM1LpnXncSDNxn5Itj89ROIgY70d2obp35K9+I+muFkAYuYJEHjtrGr7KIlC1oM+v+K43Jla4SotoBleLNbec0GwtyeYBB7bL9yhGhpEje+dtpLJFd5H/bDBuvjDg/tPHeAnflg0QfUeYfNDC44psY/uJQGBrob3eLcOdJSIV418JS+z1inC9Iljg+xkHGwWg3TSS2lD4ufZcKumBpc2S7T9XSVVB0KDeFTgyQHNDkCtG5xRb thiago@avelino.xxx

**Comment by rudaporto** [comment]
Avelino, acebei de descobrir o problema:

https://github.com/jlas/juanl.org/tree/master/planet

A mesma solução, pois o erro era o mesmo, problema com o módulo timeoutsocket.py.
Apenas removi ele do pacote planet, assim como o módulo feedparser.py (embora esse último não era necessário e precisou de um patch).

Também coloquei sua chave ssh no authorized_keys.

**Comment by rudaporto** [comment]
Faltou dizer que atualizei todos os blogs que já estavam no planet porém defasados, assim ficamos sem itens quebrados.

Segue  o comando para rodar manualmente a atualização do Planet depois de atualizar a lista de blogs:

(pythonwiki)root@wiki:/home/apyb/pythonwiki# ./bin/planetplanet etc/planet.conf

**Comment by avelino** [comment]
@rudaporto acho que podemos deixar isso ainda mais facil, colocar nosso source do planet aqui no github onde cada um manda um PR para incluir um novo blog, assim nao fica so na mao de 1 ou 2 e sim na mao da comunidade, e colocar um hook para rodar test para ver se o blog adiciona eh um feed valido e caso passe damos um git pull la na pasta e reload no servico.

Como comentei, estou aqui para ajudar (posso fazer sem problema), so preciso do seu OK e um repo git.

**Comment by avelino** [comment]
pelo que eu vi aqui o repositorio do planet seria praticamente um repo com o arquivo **planet.conf** (assim ja conseguimos solucionar isso).

Voce cria esse repo e me da acesso?

**Comment by rudaporto** [comment]
Ok, mas isso é outra issue. Tem os templates também que precisa estar no repo.

São duas issues, uma criar o repo e subir o que está lá, e outra automatizar o update.
