### ISSUE TITLE
Compartilhamento de senhas - Mitro

### ISSUE THREAD

**Issue by luizirber** [pythonbrasil/apyb.gerenciamento#76]
Criado um time no Mitro, atualmente @rochacon, @rudaporto, @luizirber, @renatooliveira e @humrochagf tem acesso (e todos tem permissão para adicionar mais pessoas ou senhas).

Escrevi o issue mais pra comunicar, mas talvez seja interessante deixar ele aberto para quando for necessário adicionar mais pessoas ao time.

**Comment by rochacon** [comment]
Boa!

Acho que podemos segurar a issue até quinta, que teremos uma reunião com mais pessoas. A partir dai fica mais fácil abrir novas issues conforme for necessário adicionar alguém.

**Comment by filipecifali** [comment]
Alguém pode me adicionar lá? Mesmo e-mail do profile. Valeu!

**Comment by luizirber** [comment]
Feito, @filipecifali

**Comment by filipecifali** [comment]
Preciso do registro.br de volta, o @rudaporto acabou me colocando as chaves lá e agora sumiu. 

Valeu!

[ ]'s

**Comment by filipecifali** [comment]
Preciso da adição desta configuração para fazer ajustes no pythonbrasil.org.br.

**Comment by humrochagf** [comment]
Adicionado @decko no time para ajudar com a manutenção da página da djangobrasil

**Comment by decko** [comment]
:+1:

**Comment by filipecifali** [comment]
@renatooliveira adicionado

**Comment by filipecifali** [comment]
@renatooliveira me enviou os dados e adicionei aos segredos do time o ID da Registro.BR

**Comment by humrochagf** [comment]
precisamos te uma nova forma de compartilhar essas chaves
https://www.mitro.co/shutdown.html

**Comment by filipecifali** [comment]
Pessoal o mitro acabará em breve, façam o backup dos dados. Caso encontrem alguma ferramenta de compartilhamento de senhas, reabram esta issue.
