### ISSUE TITLE
Feed não relacionado a Python 

### ISSUE THREAD

**Issue by ricobl** [pythonbrasil/apyb.gerenciamento#77]
Foi incluído um feed no RSS do Planeta Python Brasil que contém muitos posts não relacionados a Python.

O autor é  Eduardo Willians Bandeira de Melo. 

Acho que o ideal seria usar um RSS filtrado ou senão remover.

**Comment by rudaporto** [comment]
Sim, eu descobri como filtrar o blogspot.com e os demais wordpress, vou ajustar isso!

**Comment by ricobl** [comment]
Legal! Muito bom! Obrigado Rudá!

**Comment by ricobl** [comment]
Olá, os posts voltaram a aparecer.

**Comment by gilsondev** [comment]
Mas filtrar blogspot e wordpress somente, não prejudica aqueles que escrevem posts relacionados a Python, nessas plataformas?

**Comment by ricobl** [comment]
Estou falando deste blog em específico, o "galacia" do "Eduardo Willians Bandeira de Melo".

Aqui a postagem mais recente que neste momento está como primeira no feed:
http://galacia.blogspot.com/2015/06/consideracoes-sobre-revelacao-do-eu-sou.html

Em geral as plataformas de blogs disponibilizam feeds filtrados por labels ou categorias.

O Blogspot permite o filtro por label usando, para este blog seria esta URL:
http://galacia.blogspot.com/feeds/posts/default/-/python

**Comment by gilsondev** [comment]
Ah sim, então beleza ;)

**Comment by lskbr** [comment]
Removido.

**Comment by ricobl** [comment]
Show! Obrigado @lskbr!
