### ISSUE TITLE
Restauração de zope

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#78]
Necessário alterar DNS na registro.br para testes do plone.org.br

Não estou conseguindo gerar o output e a instância está parando sem motivos quando inicio ela.

O diretório atual está em /home/plone/buildout

Fiz os ajustes (instalação de pacotes e configuração) para que o bootstrap.py e que o ./bin/buildout funcionasse, aparentemente a instalação está ok.

**Comment by taniaa** [comment]
No ar! Com a ajudazona do grande Rudá! \o/
http://plone.python.org.br:8045/fundacao
