### ISSUE TITLE
Alteração de DNS de sites

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#79]
Servidores da Rackspace: 
    dns1.stabletransit.com
    dns2.stabletransit.com

As zonas já configuradas:
    django.org.br
    djangobrasil.org
    pythonbrasil.org.br

Peço que se alguém puder, revise.

**Comment by filipecifali** [comment]
djangobrasil.org apontando para os DNS da rackspace.

**Comment by filipecifali** [comment]
pythonbrasil.org.br movida!

**Comment by rochacbruno** [comment]
o http://python.org.br/planet/ está redirecionando para o site do evento. Está relacionado com essa issue?

**Comment by filipecifali** [comment]
Não diretamente e sim a primeira mudança para a Rackspace, preciso revisar os arquivos do nginx de rewrite pois deveria estar acessível dessa forma. 

Atualmente funciona através de wiki.python.org.br: http://wiki.python.org.br/planet/

**Comment by filipecifali** [comment]
@rochacbruno Pode testar agora? Aqui para mim ja está funcionando e faz o auto-redirect para o link que te enviei acima ;)

**Comment by filipecifali** [comment]
Zonas migradas hoje: 

python.org.br
pythonbrasil.com.br

**Comment by gilsondev** [comment]
Aqui redirecionou corretamente.

**Comment by gilsondev** [comment]
Opa, só o pythonbrasil.com.br que não.

**Comment by filipecifali** [comment]
Adicionados mapeamentos do .com.br no virtualhost do .org.br, agora está funcionando o redirecionamento Gilson

**Comment by gilsondev** [comment]
O .com.br deu como host não resolvido. Ai funcionou?

**Comment by filipecifali** [comment]
Sim, cache talvez?

**Comment by gilsondev** [comment]
Pode ser.
