### ISSUE TITLE
Integração deste repositório com Waffle.io

### ISSUE THREAD

**Issue by humrochagf** [pythonbrasil/apyb.gerenciamento#82]
Seria interessante integrar este repo com o https://waffle.io/

Desta forma fica mais fácil saber quais issues estão sendo trabalhadas e por quem, o que ajuda bastante na hora de procurar o que está precisando e atenção. 

Para integrar basta que alguém com poder de commit neste repositório vá no site e crie uma kanban board para o repositório e adicione o indicador no README.md

**Comment by decko** [comment]
:+1:
