### ISSUE TITLE
Novo Blog

### ISSUE THREAD

**Issue by nicholasamorim** [pythonbrasil/apyb.gerenciamento#85]
Olá, poderia adicionar esse blog ?

http://blog.alienretro.com/category/python-2/feed

E a bem da organização, existe um antigo blog meu no planet chamado Lambda Space que não funciona mais, caso queira remover..

Obrigado desde já.

**Comment by taniaa** [comment]
@humrochagf consegue ver no host do wiki?

**Comment by humrochagf** [comment]
@nicholasamorim @taniaa, atualizei lá
