### ISSUE TITLE
Corrigir problema de conexão com banco de dados no site das confs anteriores

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#86]
- PythonBrasil (da 1 a 6) - http://plone.python.org.br:8120/pycon

**Comment by filipecifali** [comment]
Acredito que já tenha sido corrigido, os sites estão acessíveis pelo que testei (de 2010 até 2005)

**Comment by taniaa** [comment]
Ainda está com problema. Se alguém acessa algo que precisa de conexão com o banco de dados relacional o site buga...
![captura de tela 2015-08-13 as 21 32 41](https://cloud.githubusercontent.com/assets/1102067/9264948/e5c8f206-4202-11e5-8907-72d93317e51b.png)

**Comment by taniaa** [comment]
Testando uma conf específica, de 2010 por exemplo, tb dá erro:
![captura de tela 2015-08-13 as 22 22 12](https://cloud.githubusercontent.com/assets/1102067/9265478/20733fb8-420a-11e5-9ebc-f209aae29152.png)

**Comment by rougeth** [comment]
Fechando issue, já que todos os sites da APyB foram migrados e agora são estáticos.
