### ISSUE TITLE
Subir site da PythonBrasil[8]

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#87]
Archive: https://web.archive.org/web/20121213052331/http://2012.pythonbrasil.org.br/
https://github.com/pythonbrasil/pythonbrasil8

**Comment by lskbr** [comment]
Oi Tânia,

Converti o site em versão estática. Alguns botões eu desabilitei, outros são bloqueados por pura falta de login. Mas acho que a ideia era dar a experiência do site original certo?
A vantagem da versão estática é que ele poupa recursos em nossa instância e já está pronta para a próxima migração :-D

Favor dar uma olhada, se tudo ok, feche a issue que eu limpo alguns arquivos de trabalho na máquina.

http://2012.pythonbrasil.org.br/

**Comment by lskbr** [comment]
Vou fechar. Se achares algum problema é só abrir de novo.

**Comment by taniaa** [comment]
Oi, @lskbr !

Desculpa não dar retorno. Gostei de ter tornado estático!

As pessoas corretas para validar seriam os kahunas @turicas e Tatiana.
Ou mesmo @pythonbrasil/organizacao-pythonbrasil-8.

Vou dar uma olhada assim que possível, mas não tenho muita propriedade para falar :/

**Comment by taniaa** [comment]
Acho que é isso aí!

Depois vale a pena abrir issue no projeto deste site para desabilitar pagamento de inscrição e outros detalhes de um site de evento que serve apenas como histórico...

Parabéns @lskbr !

**Comment by lskbr** [comment]
Oi Tania,

Acho que as paginas de pagamento estão com os botões desabilitados ou dão
erro 405.
Melhor coisa 'e  abrir issue mesmo, como as páginas são estáticas, podemos
corrigir um a um.

[]

Nilo

2015-08-23 5:51 GMT+02:00 Tânia Andrea notifications@github.com:
