### ISSUE TITLE
Subir vídeos da Python Brasil[8] para o Youtube

### ISSUE THREAD

**Issue by renatooliveira** [pythonbrasil/apyb.gerenciamento#89]
Pessoal, estou com os DVDs da Python Brasil que a Tati me entregou há um tempo. O problema é que não tenho como ripa-los para subir no youtube? Alguém pode fazer isso? Envio pelos correios

**Comment by rafaelgotts** [comment]
É só converter e enviar pro youtube? Isso eu posso fazer! :smiley:

**Comment by rochacbruno** [comment]
@renatooliveira acho que seria bom você fazer uma cópia dos DVDs e enviar para pelo menos 2 pessoas. Assim teriamos o trabalho paralelizado e 2 backups dos videos.

Me candidato a ser uma dessas pessoas.

**Comment by filipecifali** [comment]
@renatooliveira Fechou com o @rafaelgotts e com o @rochacbruno ?

**Comment by mazulo** [comment]
Também me candidato a ajudar nessa parte. Ou já foi resolvida?

cc @renatooliveira @rochacbruno @rafaelgotts

**Comment by rafaelgotts** [comment]
Que eu saiba não.

@rochacbruno @renatooliveira ?

**Comment by taniaa** [comment]
Aqui tem 63 vídeos da PythonBrasil6, 25 vídeos da PythonBrasil8, 38 vídeos da PythonBrasil11 e 72 vídeos da PythonBrasil12:

https://www.youtube.com/channel/UCiCQrFh8ckR_LXQyOAsOZiw/playlists
