### ISSUE TITLE
Wiki - Erro no "Esqueci senha"

### ISSUE THREAD

**Issue by diegorocha** [pythonbrasil/apyb.gerenciamento#91]
A recuperação de senha da wiki http://wiki.python.org.br/?action=recoverpass não está funcionando pois há um erro na conexão com o SMTP:

> Conexão ao servidor de correio 'localhost' falhou: [Errno 111] Connection refused

**Comment by humrochagf** [comment]
@diegorocha arrumei lá, vê se está rolando para vc de recuperar a senha

**Comment by diegorocha** [comment]
Funcionou sim!
