### ISSUE TITLE
DNS - Redirecionar para grupos locais

### ISSUE THREAD

**Issue by diegorocha** [pythonbrasil/apyb.gerenciamento#92]
Surgiu num e-mail do grupo Python-Brasil https://groups.google.com/forum/#!topic/python-brasil/A2dPdkV42so a idéia de criar um redirecionamento no dns da associação para que http://UF.pythonbrasil.org.br redirecione para o site/wiki/fórum do grupo de usuários local.

Foi respondido na thread que tal redirecionamento já existiu, mas imagino que se perdeu durante a migração de provedor.

**Comment by filipecifali** [comment]
Você tem alguma idéia de como isso funcionava?

Não encontrei configurações deste subdomínio nos HTTPDs / nGinxs

**Comment by diegorocha** [comment]
@filipecifali você já está tocando isso conforme uma thread na lista da ApyB.

Acho que o padrão que você sugeriu é muito bom e atende os casos de um grupo só por estado, com ou sem grupo de cidades ou regiões.

http://[cidade/regiao.]uf.python.org.br

Acho que essa issue em específico pode ser fechada, já que a questão está andando. Não faz sentido deixar ela aberta até que todos os grupos locais existentes estejam com subdomínio funcionando.

Cada grupo que queira ter um subdomínio no registro python.org.br pode abrir uma issue individual e um voluntário com acesso ao dns cria o cname.

**Comment by luzfcb** [comment]
Falta documentar isso (`http://[cidade/regiao.]uf.python.org.br`), deixar essa informação em um lugar publico e acessível e fazer marketing, incluindo os procedimentos necessários que cada grupo quiser utilizar o subdominio tem que fazer.

**Comment by diegorocha** [comment]
Verdade @luzfcb existe hoje algum lugar oficial da associação para documentar esse tipo de coisa?
O site da associação seria o melhor lugar para esse marketing, com uma página explicando.

Que eu saiba atualmente a forma de gerar demandas é abrindo um ticket aqui, então a página precisaria colocar um link para esse repositório e dizer quais informações devem ser informadas na hora de abrir uma issue para isso (o nome do grupo, o host para apontar, por exemplo).
