### ISSUE TITLE
Adição no planeta

### ISSUE THREAD

**Issue by smateusjr** [pythonbrasil/apyb.gerenciamento#93]
Prezados boa noite,

Meu nome é Sérgio Mateus, trabalho com tecnologia há mais de 10 anos e
tenho a pretensão de ir me mudar do Brasil para o Canadá em no máximo 5
anos, em uma palestra para imigrantes foi me informado de que precisaria de
"mostrar serviço", como um GITHUB ou um portifólio online, então resolvi
abrir um Blog com alguns projetos pessoais e informações do meu trabalho,
como acompanho o "Planet Geek" a alguns anos e alguns outros "Planet",
gostaria de saber se póssivel meu Blog ser um dos assinantes, só tenho uma
postagem, mas é de meu grande interesse que ele cresça pois é uma meta de
vida.

Ele é todo feito em python com django/zinnia.

http://www.sergiomateus.ca

Desde já agradeço a oportunidade

**Comment by taniaa** [comment]
Feito com feed: http://www.sergiomateus.ca/feeds/
