### ISSUE TITLE
Corrigir dependência do site PythonBrasil[9]/PloneConf 2013

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#94]
Este erro deu ao tentar gerar o certificado.

Traceback (innermost last):

```
Module ZPublisher.Publish, line 60, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module grokcore.view.components, line 101, in __call__
Module zope.publisher.publish, line 107, in mapply
__traceback_info__: <bound method Generate.render of <apyb.conference.browser.certificate.Generate object at 0x7fa9dccf2ed0>>
Module zope.publisher.publish, line 113, in debug_call
Module apyb.conference.browser.certificate, line 96, in render
Module apyb.conference.browser.certificate, line 60, in generate
Module PIL.ImageFont, line 218, in truetype
Module PIL.ImageFont, line 134, in __init__
Module PIL.ImageFont, line 34, in __getattr__
```

ImportError: The _imagingft C module is not installed

**Comment by gilsondev** [comment]
Precisa compiilar o PIL habilitando o uso da biblioteca `libfreetype`

**Comment by filipecifali** [comment]
Tania, instalei a libfreetype6 e a -dev dela e reinstalei a Pillow, pode efetuar um teste de novo? \* Não sei se seria necessário reiniciar a instância, caso sim, posso fazer isso também *

**Comment by taniaa** [comment]
Obrigada @filipecifali, mas continua com erro. Pode reiniciar a instância. Te enviei o link em PVT para teste, porque é o link que gera o certificado de um participante específico.

**Comment by rougeth** [comment]
Fechando issue, já que todos os sites da APyB foram migrados e agora são páginas estáticas.
