### ISSUE TITLE
Correção de link - wiki.python.org.br/planet

### ISSUE THREAD

**Issue by filipecifali** [pythonbrasil/apyb.gerenciamento#95]
http://wiki.python.org.br/planet/

Header aponta para 2014 - pythonbrasil 10

**Comment by taniaa** [comment]
Corrigido.

**Comment by lskbr** [comment]
Abri hoje e continua apontando para PythonBrasil 10

**Comment by taniaa** [comment]
Deve ser cache na sua máquina. Segue print.
![captura de tela 2015-08-12 as 09 50 20](https://cloud.githubusercontent.com/assets/1102067/9224291/a010fa50-40d7-11e5-8171-b9105f9fce75.png)

**Comment by taniaa** [comment]
De fato. Eu estava vendo wiki.python.org.br/ e vocês vendo wiki.python.org.br/planet. Então mudei o título do ticket para /planet e vou tentar resolver no servidor...

**Comment by taniaa** [comment]
Trocado http://wiki.python.org.br/planet/, veja o print
![captura de tela 2015-08-12 as 10 28 50](https://cloud.githubusercontent.com/assets/1102067/9224998/fac6431a-40dc-11e5-88a4-fb32d649d50d.png)

Como não tenho um logo pybr_logo_pt-br.png com dimensões de 507×66 pixels e não encontrei um logo nos padrões no site do evento deste ano, coloquei textual mesmo o link para a PythonBrasil[11].

@cadu-leite pode me enviar dois logos? Um conforme o que descrevi acima[1] e outro conforme ticket de ontem[2] para o site da APYB?
[1] https://github.com/pythonbrasil/pythonbrasil11/issues/10
[2] https://github.com/pythonbrasil/pythonbrasil11/issues/9

Obrigada!

**Comment by taniaa** [comment]
E procedimento documentado no site da APyB:

http://plone.python.org.br:8045/fundacao/workarea/procedimentos-web/gestao-do-wiki/como-mudar-a-chamada-para-a-conferencia-anual-no-topo-da-pagina-do-planet
