### ISSUE TITLE
Documentar o passo a passo de inclusão de URL no Planet

### ISSUE THREAD

**Issue by taniaa** [pythonbrasil/apyb.gerenciamento#96]

**Comment by taniaa** [comment]
Adicionei o procedimento aqui, conforme passo a passo que o @humrochagf me enviou:
http://plone.python.org.br:8045/fundacao/workarea/procedimentos-web/gestao-do-wiki/como-incluir-uma-nova-url-no-planet

Porém, para ajudar quem está chegando e não depender de 2 ou 3 pessoas, acho melhor adicionar do comando para login no servidor à detalhar o comando no moin...

@rudaporto @osantana @humrochagf @filipecifali podem me ajudar a detalhar mais este procedimento?

**Comment by taniaa** [comment]
Tudo devidamente documentado com a ajuda do @humrochagf, na mesma URL.

**Comment by lskbr** [comment]
Tânia, como faço para acessar essa página? Eu não tenho conta no plone.
Hoje eu deu uma limpada no planet e olhei bastante coisa por lá.

**Comment by taniaa** [comment]
Te mandei por e-mail, por ter conta no server já.

O passo a passo está privado porque ter dados do servidor...
