### ISSUE TITLE
Atualizar o estatuto no site da associação

### ISSUE THREAD

**Issue by diegorocha** [pythonbrasil/apyb.gerenciamento#97]
É necessário atualizar o estatuto presente no site  http://associacao.python.org.br/fundacao/associacao/estatuto
 para o novo estatuto após as alterações aprovadas em https://github.com/pythonbrasil/estatuto/blob/master/assembleia-2013/ata-008-draft.md

Acredito que o melhor seria que essa página tivesse um link para o markdown do estatuto no github https://github.com/pythonbrasil/estatuto/blob/master/README.rst pois, caso haja nova mudança não será preciso atualizar a página já que esse link sempre terá a versão atual do estatuto.

**Comment by rougeth** [comment]
Site atual contém estatuto atualizando.
