### ISSUE TITLE
Atualizar o site de associados

### ISSUE THREAD

**Issue by lskbr** [pythonbrasil/apyb.gerenciamento#98]
- Atualizar Django para 1.8
- Adicionar página de estatísticas
- Adicionar marcador para membros plenos
- Adicionar filtro para exibir a diretoria

**Comment by gilsondev** [comment]
Também definir a issue #97 nas melhorias.

**Comment by taniaa** [comment]
Muito legal estas features!

Lembro de ter comentado que o primeiro já resolveu:
- Atualizar Django para 1.8

Como estão as demais tarefas? O @gilsondev comentou que queria ajudar com o sistema. Consegue validar o que ele trabalhou?
https://github.com/pythonbrasil/associados/pull/118

**Comment by gilsondev** [comment]
A próxima issue pode ser a atualização do django.

**Comment by taniaa** [comment]
Não entendi @gilsondev

**Comment by gilsondev** [comment]
Desculpe, eu pretendo atualizar o associados para o django 1.8.

**Comment by lskbr** [comment]
Gilson, a migração para o Django 1.8 já está feita.

**Comment by lskbr** [comment]
Eu estou trabalhando neste issue, se você quiser, eu posso parar e você continua.

**Comment by lskbr** [comment]
Desculpa, repondi rápido demais. Eu me atribui este issue e gostaria de continuar nele.

**Comment by gilsondev** [comment]
Não precisa @lskbr. Mas no que precisa, estamos ai :)

**Comment by lskbr** [comment]
Beleza Gilson, eu vou precisar de uma força para fazer o deploy no heroku, mas se for o caso, eu abro outro issue! Valeu.

**Comment by gilsondev** [comment]
:+1:

**Comment by lskbr** [comment]
Um update. Acabei de atualizar tudo para o Django 1.8.4.
Todos os testes estão passando.

Criei um branch django1.8 com a versão de hoje. A versão atual está incompleta. Estou falando com o Carlos sobre a integração do django municípios (permite usar 2 selects com estados e municípios do Brasil). Já aparece, mas não grava.

Eu melhorei o tempo de carga da listagem de membros. Agora eu faço cache das urls. Depois vou criar uma task para atualizar as url das imagens. Nós estávamos fazendo umas 60 queries por página e umas 60 requisições ao github a cada página. Já resolvi isso. Agora são apanas 3 queries e as urls vem do cache ou do github.

Para melhorar os problemas de layout, eu retirei a organização, mas deixei o blog. O tempo caiu de 2s para 20 ms :-D

**Comment by gilsondev** [comment]
Massa ;)

**Comment by lskbr** [comment]
Pessoal, eu tive alguns problemas, principalmente devido a criação de uma nova associação que participo. Mas devo voltar a trabalhar nos fontes o quanto antes.

**Comment by taniaa** [comment]
Legal!

**Comment by gilsondev** [comment]
@lskbr quando fui rodar o `make run` deu esse erro:

``` bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gilson/Developer/.virtualenvs/associados_pybr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/gilson/Developer/.virtualenvs/associados_pybr/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/gilson/Developer/.virtualenvs/associados_pybr/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gilson/Developer/.virtualenvs/associados_pybr/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: debug_toolbar
Makefile:8: recipe for target 'run' failed
make: *** [run] Error 1
```

Aconteceu contigo?

**Comment by lskbr** [comment]
Não Gilson, você está executando do branch?
Acho que a última versão do django que utilizei com o branch foi a 1.8.4. Tem um bug no componente de escolher cidades, mas não lembro deste que você teve. Talvez eu tenha esquecido de subir algum arquivo. Diga se é crítico para você ou se posso fazer só no fim de semana.

**Comment by gilsondev** [comment]
estou usando a branch django1.8

**Comment by gilsondev** [comment]
Não é critico não, estou iniciando a documentação do projeto na parte de:
- Introdução do projeto
- Arquitetura
- Configuração

**Comment by lskbr** [comment]
Beleza! Muito bom ter a documentação.
Vou voltar a trabalhar no código e testo esse bug. Até o fim de semana te
atualizo.

2015-11-16 23:23 GMT+01:00 Gilson Filho notifications@github.com:

**Comment by lskbr** [comment]
O site foi terminado ano passado. A migração para Django 1.8 foi realizada e algumas melhorias implementadas como: uso de um banco de dados para normalizar cidades/municipios e estados e melhoria na carga da página que lista as fotos de cada membro (chamadas a api do gravatar foram adicionadas ao cache). O deploy está com o Cadu.
