### ISSUE TITLE
Alteração de feed no planet

### ISSUE THREAD

**Issue by rochacbruno** [pythonbrasil/apyb.gerenciamento#99]
Olá, gostaria de solicitar a alteração do meu link no planet 
de: http://feeds.feedburner.com/rochacbruno  

**para**: http://brunorocha.org/tag/pyplanet.atom

(duvida: seria legal ter um repositório com o código do planet igual fazemos com o planet.python.org? https://github.com/python/planet )

**Comment by filipecifali** [comment]
Seria, o Humberto já tinha me perguntado sobre uma forma melhor de dar manutenção no planet.python.org.br, no gtalk ele me mandou:

"poise, da forma que está não tá muito legal pq isso é um pedido recorrente, btf que vou colocar uma git hook lá e botar a lista de feed num repo da APyB pra galera poder atualizar com pull request"

Isso é bem bacana, seria muito mais prático para qualquer um atualizar com permissão de merge nos PRs

**Comment by lskbr** [comment]
Felipe,

Seria legal também fazer uma limpeza no Planet. Hoje mesmo tem oração,
coisa de lua e outros bichos no feed.
Eu lembro que só seriam incluídos os posts com uma tag específica, mas acho
que isto não esta funcionando.

A macro que incluia os 5 últimos posts na Wiki estava matando o servidor.
Se precisar acessar o planet, até resovermos o problema, favor acessar:
http://wiki.python.org.br/planet/

[]

Nilo

2015-08-12 16:51 GMT+02:00 Filipe Cifali Stangler notifications@github.com
:

**Comment by lskbr** [comment]
Coloquei um link em seções interessantes da Wiki para o planet como
quebra-galho :-D

2015-08-12 20:30 GMT+02:00 Nilo Menezes nilo.menezes@gmail.com:

**Comment by rochacbruno** [comment]
Lelgal :+1:  e a alteração do feed quem faz? e como?

**Comment by humrochagf** [comment]
Então como os feeds vem de um arquivo de texto seria uma boa colocar esse arquivo em um repositório e atualizar via PullRequest, ai coloca um travisCI pra toda vez que um PR for aceito ele rodar o script de refresh do planet no servidor

**Comment by lskbr** [comment]
Feed alterado.
